#!/usr/bin/env bash
# Regenerates src/Files.App/Platforms/Desktop/Generated/ICommandManager.g.cs.
#
# Uno's XAML generator cannot see members emitted by other Roslyn generators, so x:Bind to ICommandManager
# only works against a checked-in copy. Run this after adding or removing a [GeneratedRichCommand] action.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
out="$(mktemp -d)"
target="$root/src/Files.App/Platforms/Desktop/Generated/ICommandManager.g.cs"

# Build without the pre-generated copy so the generator emits its own; XAML errors are expected and ignored.
mv "$target" "$target.bak"
trap 'mv -f "$target.bak" "$target" 2>/dev/null || true' EXIT
dotnet build "$root/src/Files.App" -f net10.0-desktop -p:FilesPregeneratedICommandManager=false \
	-p:EmitCompilerGeneratedFiles=true -p:CompilerGeneratedFilesOutputPath="$out" > /dev/null || true

generated="$(find "$out" -name ICommandManager.g.cs | head -n 1)"
[ -n "$generated" ] || { echo "ICommandManager.g.cs was not generated" >&2; exit 1; }

{
	echo "// <auto-generated/>"
	echo "// Snapshot of the interface emitted by CommandManagerGenerator. Do not edit; run scripts/linux/regen-command-manager.sh."
	tail -n +2 "$generated"
} > "$target.new"
mv -f "$target.new" "$target"
rm -f "$target.bak"
trap - EXIT
echo "Updated $target"
