<!--  Copyright (c) Files Community. Licensed under the MIT License.  -->
<Project>
  <PropertyGroup>

    <!--  Generic properties  -->
    <BaseTargetFramework>net10.0</BaseTargetFramework>
    <TargetWindowsVersion>10.0.26100.0</TargetWindowsVersion>
    <MinimalWindowsVersion>10.0.19041.0</MinimalWindowsVersion>
    <WindowsSdkPackageVersion>10.0.26100.67-preview</WindowsSdkPackageVersion>
    <WindowsTargetFramework>$(BaseTargetFramework)-windows$(TargetWindowsVersion)</WindowsTargetFramework>
    <DesktopTargetFramework>$(BaseTargetFramework)-desktop</DesktopTargetFramework>
    <LangVersion>preview</LangVersion>
    <WarningsAsErrors>nullable</WarningsAsErrors>

    <!--  Use Microsoft.Testing.Platform  -->
    <EnableMSTestRunner>true</EnableMSTestRunner>

    <!--  Use strict Roslyn compilation mode  -->
    <Features>strict</Features>

    <!--  Enable all C#/WinRT trimming and NativeAOT diagnostics  -->
    <CsWinRTAotWarningLevel>3</CsWinRTAotWarningLevel>

  </PropertyGroup>
</Project>
