// Copyright (c) Files Community
// Licensed under the MIT License.

namespace Files.Core.SourceGenerator.Generators
{
	/// <summary>
	/// A minimal stand-in for CommunityToolkit.Labs' <c>[GeneratedDependencyProperty]</c> generator, used only when
	/// building against Uno Platform (the Toolkit generator depends on WinAppSDK-only APIs and silently emits nothing on Uno).
	/// Opt-in through the <c>FilesUnoDependencyProperty</c> MSBuild property so Windows builds are never affected.
	/// </summary>
	[Generator]
	internal sealed class UnoDependencyPropertyGenerator : IIncrementalGenerator
	{
		private const string AttributeName = "GeneratedDependencyProperty";

		private sealed record Item(
			string? Namespace,
			string TypeName,
			string TypeKeyword,
			string PropertyName,
			string PropertyType,
			string Accessibility,
			string? DefaultValueExpression,
			string? SetterAccessibility);

		public void Initialize(IncrementalGeneratorInitializationContext context)
		{
			var enabled = context.AnalyzerConfigOptionsProvider.Select(static (p, _) =>
				p.GlobalOptions.TryGetValue("build_property.FilesUnoDependencyProperty", out var v) &&
				string.Equals(v, "true", StringComparison.OrdinalIgnoreCase));

			var items = context.SyntaxProvider.CreateSyntaxProvider(
				static (node, _) => node is PropertyDeclarationSyntax { AttributeLists.Count: > 0 },
				static (ctx, ct) => Transform(ctx, ct))
				.Where(static i => i is not null)
				.Select(static (i, _) => i!);

			context.RegisterSourceOutput(items.Collect().Combine(enabled), static (ctx, pair) =>
			{
				if (!pair.Right)
					return;

				foreach (var group in pair.Left.GroupBy(i => (i.Namespace, i.TypeName, i.TypeKeyword)))
				{
					var sb = new StringBuilder();
					_ = sb.AppendLine("// <auto-generated/>");
					_ = sb.AppendLine("#nullable enable");
					_ = sb.AppendLine("#pragma warning disable");
					_ = sb.AppendLine();
					var indent = "";
					if (group.Key.Namespace is not null)
					{
						_ = sb.AppendLine($"namespace {group.Key.Namespace}");
						_ = sb.AppendLine("{");
						indent = "\t";
					}

					_ = sb.AppendLine($"{indent}partial {group.Key.TypeKeyword} {group.Key.TypeName}");
					_ = sb.AppendLine($"{indent}{{");

					foreach (var i in group)
					{
						var t = i.PropertyType;
						var dp = $"{i.PropertyName}Property";
						var tNonNull = t.TrimEnd('?');
						var defaultExpr = i.DefaultValueExpression is null
							? $"default({t})"
							: $"({t})({i.DefaultValueExpression})";

						_ = sb.AppendLine($"{indent}\t/// <summary>Identifies the <see cref=\"{i.PropertyName}\"/> dependency property.</summary>");
						_ = sb.AppendLine($"{indent}\tpublic static readonly global::Microsoft.UI.Xaml.DependencyProperty {dp} = global::Microsoft.UI.Xaml.DependencyProperty.Register(");
						_ = sb.AppendLine($"{indent}\t\tnameof({i.PropertyName}), typeof({tNonNull}), typeof({i.TypeName}),");
						_ = sb.AppendLine($"{indent}\t\tnew global::Microsoft.UI.Xaml.PropertyMetadata((object?){defaultExpr}, static (d, e) =>");
						_ = sb.AppendLine($"{indent}\t\t{{");
						_ = sb.AppendLine($"{indent}\t\t\tvar self = ({i.TypeName})d;");
						_ = sb.AppendLine($"{indent}\t\t\tself.On{i.PropertyName}Changed(({t})e.NewValue);");
						_ = sb.AppendLine($"{indent}\t\t\tself.On{i.PropertyName}Changed(({t})e.OldValue, ({t})e.NewValue);");
						_ = sb.AppendLine($"{indent}\t\t\tself.On{i.PropertyName}PropertyChanged(e);");
						_ = sb.AppendLine($"{indent}\t\t}}));");
						_ = sb.AppendLine();
						_ = sb.AppendLine($"{indent}\t{i.Accessibility} partial {t} {i.PropertyName}");
						_ = sb.AppendLine($"{indent}\t{{");
						_ = sb.AppendLine($"{indent}\t\tget => ({t})GetValue({dp});");
						_ = sb.AppendLine($"{indent}\t\t{(i.SetterAccessibility is null ? "" : i.SetterAccessibility + " ")}set => SetValue({dp}, value);");
						_ = sb.AppendLine($"{indent}\t}}");
						_ = sb.AppendLine();
						_ = sb.AppendLine($"{indent}\tpartial void On{i.PropertyName}Changed({t} newValue);");
						_ = sb.AppendLine($"{indent}\tpartial void On{i.PropertyName}Changed({t} oldValue, {t} newValue);");
						_ = sb.AppendLine($"{indent}\tpartial void On{i.PropertyName}PropertyChanged(global::Microsoft.UI.Xaml.DependencyPropertyChangedEventArgs e);");
						_ = sb.AppendLine();
					}

					_ = sb.AppendLine($"{indent}}}");
					if (group.Key.Namespace is not null)
						_ = sb.AppendLine("}");

					ctx.AddSource($"{group.Key.Namespace}.{group.Key.TypeName}.UnoDP.g.cs".TrimStart('.'), SourceText.From(sb.ToString(), Encoding.UTF8));
				}
			});
		}

		private static Item? Transform(GeneratorSyntaxContext ctx, System.Threading.CancellationToken ct)
		{
			var syntax = (PropertyDeclarationSyntax)ctx.Node;
			if (!syntax.Modifiers.Any(SyntaxKind.PartialKeyword))
				return null;

			if (ctx.SemanticModel.GetDeclaredSymbol(syntax, ct) is not IPropertySymbol symbol)
				return null;

			var attr = symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == AttributeName + "Attribute");
			if (attr is null)
				return null;

			string? defaultExpr = null;
			var attrSyntax = syntax.AttributeLists.SelectMany(l => l.Attributes)
				.FirstOrDefault(a => a.Name.ToString().StartsWith(AttributeName));
			var arg = attrSyntax?.ArgumentList?.Arguments.FirstOrDefault(a => a.NameEquals?.Name.Identifier.Text == "DefaultValue");
			if (arg is not null)
			{
				// Fully qualify enum members (e.g. a property named SweepDirection of type SweepDirection makes "SweepDirection.Clockwise" ambiguous)
				defaultExpr = ctx.SemanticModel.GetSymbolInfo(arg.Expression, ct).Symbol is IFieldSymbol { IsConst: true, ContainingType.TypeKind: TypeKind.Enum } field
					? $"{field.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}.{field.Name}"
					: arg.Expression.ToString();
			}

			var type = symbol.ContainingType;
			var fmt = SymbolDisplayFormat.FullyQualifiedFormat.AddMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);
			var ns = type.ContainingNamespace is { IsGlobalNamespace: false } n ? n.ToDisplayString() : null;

			string Acc(Accessibility a) => a switch
			{
				Accessibility.Public => "public",
				Accessibility.Internal => "internal",
				Accessibility.Protected => "protected",
				Accessibility.Private => "private",
				Accessibility.ProtectedOrInternal => "protected internal",
				Accessibility.ProtectedAndInternal => "private protected",
				_ => "public",
			};

			var propAcc = symbol.DeclaredAccessibility;
			var setAcc = symbol.SetMethod is { } sm && sm.DeclaredAccessibility != propAcc ? Acc(sm.DeclaredAccessibility) : null;

			return new Item(
				ns,
				type.Name,
				type.TypeKind == TypeKind.Struct ? "struct" : "class",
				symbol.Name,
				symbol.Type.ToDisplayString(fmt),
				Acc(propAcc),
				defaultExpr,
				setAcc);
		}
	}
}
