<!--  Copyright (c) Files Community. Licensed under the MIT License.  -->
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release</Configurations>
        <DefineConstants>$(DefineConstants);DESKTOP</DefineConstants>
        <Platforms>x86;x64;arm64</Platforms>
        <RuntimeIdentifiers>win-x86;win-x64;win-arm64;linux-x64;linux-arm64</RuntimeIdentifiers>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="UTF.Unknown" />
        <PackageReference Include="ColorCode.Core" />
        <PackageReference Include="TagLibSharp" />
        <PackageReference Include="MSTest.TestAdapter" />
        <PackageReference Include="MSTest.TestFramework" />
        <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Files.Platform.Abstractions\Files.Platform.Abstractions.csproj" />
        <ProjectReference Include="..\..\src\Files.Platform.Linux\Files.Platform.Linux.csproj" />
        <ProjectReference Include="..\..\src\Files.Core.Storage\Files.Core.Storage.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="../../src/Files.App/ViewModels/UserControls/Previews/PreviewTextReader.cs" Link="Previews/PreviewTextReader.cs" />
        <Compile Include="../../src/Files.App/ViewModels/UserControls/Previews/CodeLanguageMap.cs" Link="Previews/CodeLanguageMap.cs" />
        <Compile Include="../../src/Files.App/ViewModels/UserControls/Previews/PreviewCodeTokenizer.cs" Link="Previews/PreviewCodeTokenizer.cs" />
        <Compile Include="../../src/Files.App/ViewModels/UserControls/Previews/PreviewImageDecoder.cs" Link="Previews/PreviewImageDecoder.cs" />
        <Compile Include="../../src/Files.App.Storage/Storables/Routes/*.cs" LinkBase="Storables/Routes" />
    </ItemGroup>

</Project>
