<!--  Copyright (c) Files Community. Licensed under the MIT License.  -->
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Configurations>Debug;Release</Configurations>
        <DefineConstants>$(DefineConstants);DESKTOP</DefineConstants>
        <Platforms>x86;x64;arm64</Platforms>
        <RuntimeIdentifiers>win-x86;win-x64;win-arm64;linux-x64;linux-arm64</RuntimeIdentifiers>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="UTF.Unknown" />
        <PackageReference Include="ColorCode.Core" />
        <PackageReference Include="TagLibSharp" />
        <PackageReference Include="FluentFTP" />
        <PackageReference Include="MSTest.TestAdapter" />
        <PackageReference Include="MSTest.TestFramework" />
        <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Files.Platform.Abstractions\Files.Platform.Abstractions.csproj" />
        <ProjectReference Include="..\..\src\Files.Platform.Linux\Files.Platform.Linux.csproj" />
        <ProjectReference Include="..\..\src\Files.Core.Storage\Files.Core.Storage.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="../../src/Files.App/ViewModels/UserControls/Previews/PreviewTextReader.cs" Link="Previews/PreviewTextReader.cs" />
        <Compile Include="../../src/Files.App/ViewModels/UserControls/Previews/CodeLanguageMap.cs" Link="Previews/CodeLanguageMap.cs" />
        <Compile Include="../../src/Files.App/ViewModels/UserControls/Previews/PreviewCodeTokenizer.cs" Link="Previews/PreviewCodeTokenizer.cs" />
        <Compile Include="../../src/Files.App/ViewModels/UserControls/Previews/PreviewImageDecoder.cs" Link="Previews/PreviewImageDecoder.cs" />
        <Compile Include="../../src/Files.App.Storage/Storables/Routes/*.cs" LinkBase="Storables/Routes" />
        <Compile Include="../../src/Files.App.Storage/Ftp/FtpUrl.cs;../../src/Files.App.Storage/Ftp/FtpManager.cs;../../src/Files.App.Storage/Ftp/FtpStorableRoute.cs;../../src/Files.App.Storage/Ftp/FtpClientFactory.cs" LinkBase="Storables/Ftp" />
        <Compile Include="../../src/Files.App/Data/Enums/FilesystemItemType.cs" Link="Storables/FilesystemItemType.cs" />
        <Compile Include="../../src/Files.App/Utils/Storage/Helpers/IStorageItemWithPath.cs" Link="Storables/IStorageItemWithPath.cs" />
        <Compile Include="../../src/Files.App/Utils/Storage/Helpers/StorableWithPath.cs" Link="Storables/StorableWithPath.cs" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="../../src/Files.App.Storage/Archives/*.cs" LinkBase="Archives/Storables" />
        <Compile Include="../../src/Files.Shared/Helpers/FileExtensionHelpers.cs" Link="Archives/FileExtensionHelpers.cs" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="../../src/Files.App/Utils/Serialization/ISettingsSerializer.cs" Link="Settings/ISettingsSerializer.cs" />
        <Compile Include="../../src/Files.App/Utils/Serialization/IJsonSettingsSerializer.cs" Link="Settings/IJsonSettingsSerializer.cs" />
        <Compile Include="../../src/Files.App/Utils/Serialization/IJsonSettingsDatabase.cs" Link="Settings/IJsonSettingsDatabase.cs" />
        <Compile Include="../../src/Files.App/Utils/Serialization/Implementation/*.cs" LinkBase="Settings/Implementation" />
    </ItemGroup>
</Project>
